

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor]
true-color = true
mouse = false
